config/routes.rb
Rails.application.routes.draw do
  get 'raffle_entries/create'

  get 'raffle_entries/index'

  devise_for :admins, controllers: {
        sessions: 'admins/sessions'
      }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    root to: "raffle_entries#index"
    resources :raffle_entries, only: [:index, :new, :create]

    patch '/draw', to: 'raffle_entries#draw'
    get '/results', to: 'raffle_entries#raffle_results'
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/exercise.rb
class Exercise < ApplicationRecord
end

app/models/raffle_entry.rb
class RaffleEntry < ApplicationRecord
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true, unless: :phone
  validates :phone, presence: true, unless: :email
  validates :exercise, presence: true
  validates :repetitions, presence: true 
end

app/models/result.rb
class Result < ApplicationRecord
end

app/controllers/admins/confirmations_controller.rb
# frozen_string_literal: true

class Admins::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/admins/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Admins::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/admins/passwords_controller.rb
# frozen_string_literal: true

class Admins::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/admins/registrations_controller.rb
# frozen_string_literal: true

class Admins::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    super
  end

  # POST /resource
  def create
    super
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  def destroy
    super
  end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/admins/sessions_controller.rb
# frozen_string_literal: true

class Admins::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  def new
    super
  end

  # POST /resource/sign_in
  def create
    super
  end

  # DELETE /resource/sign_out
  def destroy
    super
  end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/admins/unlocks_controller.rb
# frozen_string_literal: true

class Admins::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
end

app/controllers/raffle_entries_controller.rb
class RaffleEntriesController < ApplicationController

  def create
    raffle = RaffleEntry.new(first_name: params[:first_name], last_name: params[:last_name] ,email: params[:email] ,phone: params[:phone] ,exercise: params[:exercise] ,repetitions: params[:repetitions]  )
    raffle.save ? flash[:success] = "Raffle Entry Saved" : flash[:error] = "#{raffle.errors.full_messages.first}"
    redirect_to '/'
  end

  def new

  end

  def index
    @scores = RaffleEntry.where("created_at > ?", 1.days.ago.beginning_of_day).map {|n| n.repetitions.to_i}.sum
    @pushups = RaffleEntry.where(exercise: "Push-Ups").map {|n| n.repetitions.to_i}.sum
    @pullups = RaffleEntry.where(exercise: "Pull-Ups").map {|n| n.repetitions.to_i}.sum
    @crunches = RaffleEntry.where(exercise: "Crunches").map {|n| n.repetitions.to_i}.sum
    @lunges = RaffleEntry.where(exercise: "Lunges").map {|n| n.repetitions.to_i}.sum
    @squats = RaffleEntry.where(exercise: "Squats").map {|n| n.repetitions.to_i}.sum
  end

  def raffle_results
    @results = RaffleEntry.where(winner: true)
    render 'raffle_results.html.erb'
  end

  def draw
    if current_admin && current_admin.master == 1
      draw = RaffleEntry.all.shuffle.sample(20)
      draw.map{|winner| winner.update(winner: true)}
      redirect_to '/results'
    else
      flash[:error] = "No Permission To Draw Raffle"
      @results = RaffleEntry.where(winner: true)
      render 'raffle_results.html.erb'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/raffle_entries_helper.rb
module RaffleEntriesHelper
end

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OdysseyRaffle</title>
    <%= csrf_meta_tags %>
    <%= favicon_link_tag asset_path('favicon.ico'), :rel => 'icon', :type => "image/x-icon" %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>


  	<!-- Theme style  -->
  	<link rel="stylesheet" href="/css/style.css">
  	<!-- Modernizr JS -->
  	<script src="js/modernizr-2.6.2.min.js"></script>
    <body>

  	<header id="home">
      <div class="row">
        <div class="col-xs-10 col-xs-offset-1">
          <% flash.each do |name, message| %>
            <div class="alert alert-<%= name %> alert-dismissible flash" role="alert">
              <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <%= message %>
          <% end %>
        </div>
      </div>
  		<div class="container">
  			<div class="col-md-6 col-sm-6" id="title">
  				<div class="intro">
            <h1 id="fh5co-logo">Odyssey House Fitness Raffle</h1>
            <p>
              <ul>
              <% if admin_signed_in? %>
              <!-- New Entry -->
                <li class="btn btn-primary"><%= link_to "New Entry", "raffle_entries/new" %> </li>
                <li class="btn btn-primary"> <%= link_to "Logout", "/admins/sign_out", method: :delete %></li>
                <li class="btn btn-primary"> <%= link_to "Raffle Drawing", "/results" %></li>
                <% else %>
                <li class="btn btn-primary"> <%= link_to "Login", "/admins/sign_in" %> </li>
                <% end %>
              </ul>
            </p>
  				</div>
  			</div>
        <div class="col-md-6 col-sm-6 scores">
          <%= yield %>
        </div>
  		</div>
  	</header>
  	</body>

</html>

app/views/raffle_entries/index.html.erb
<p><span id="rep-count"><%= @scores %> </span>Reps Done Today!</p>
<p><span id="rep-count"><%= @pullups %></span> Pullups</p>
<p><span id="rep-count"><%= @pushups %></span> Pushups</p>
<p><span id="rep-count"> <%= @lunges %></span> Lunges</p>
<p><span id="rep-count"> <%= @squats %></span> Squats</p>
<p><span id="rep-count"> <%= @crunches %></span> Crunches</p>

app/views/raffle_entries/new.html.erb
<h1>New Participant</h1>
<%= form_tag "/raffle_entries", method: :post do %>
<p><input type="text" name="first_name" placeholder="First Name" value=""> </p>
<p><input type="text" name="last_name" placeholder="Last Name" value=""> </p>
<p><input type="email" name="email" placeholder="Email" value=""> </p>
<p><input type="tel" name="phone" placeholder="phone number" value=""> </p>
<p>
  <select name="exercise">
    <option name="exercise" value="Lunges">Lunges</option>
    <option name="exercise" value="Pull-Ups">Pull-Ups</option>
    <option name="exercise" value="Crunches">Crunches</option>
    <option name="exercise" value="Squats">Squats</option>
    <option name="exercise" value="Push-Ups">Push-Ups</option>
  </select>
</p>

<p><input type="integer" name="repetitions" placeholder="reps" value=""> </p>
<p><input type="submit" value="Submit"> </p>

<% end %>

app/views/raffle_entries/raffle_results.html.erb
<h1>Our Winners</h1>
<table>
  <thead>

  <tr>
    <% if current_admin.master == 1 %>
      <th>Email</th>
      <th>Phone</th>
    <% end %>
      <th>Name</th>
    </tr>
  </thead>
  <% @results.each do |winner| %>
    <tr scope="row">
      <% if current_admin.master == 1 %>
      <td><%= winner.email %></td>
      <td><%= winner.phone %></td>
      <% end %>
      <td><%= winner.first_name %> <%= winner.last_name %></td>
    </tr>
  <% end %>
</table>

<%= form_tag '/draw', method: :patch do%>
<input class="btn btn-primary submit" type="submit" value="Draw Winners">
<% end %>